# Generated by Django 5.1.1 on 2024-09-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Ruoli',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('ruolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persone', to='soci.ruolo')),
            ],
            options={
                'verbose_name_plural': 'Persone',
            },
        ),
    ]
