# Generated by Django 5.1.1 on 2024-09-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': 'libri'},
        ),
    ]
